AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Lambda Gin
Parameters:
  functionname:
    Type: String
    Default: 'lambdawithgo-test'
Resources:
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:  !Sub '${functionname}'
      Handler: main
      CodeUri: main.zip
      Runtime: go1.x
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 3
      Role: arn:aws:iam::699085892706:role/AwsLambdaDeployRole
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /
            Method: post


Outputs:
  SampleGinApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
    Export:
      Name: !Sub '${functionname}'
